
∇DERR T
  ⍝ IF  T  IS FALSE, A MESSAGE IS PRINTED AND ALL ACTIVE
  ⍝ PROCEDURES ARE TERMINATED.
  →T/0
  'PROCEDURE DOMAIN ERROR'
  →
∇

∇W←SSORT V
  ⍝ SORTS A VECTOR INTO INCREASING ORDER AND REMOVES
  ⍝ DUPLICATES.
  DERR 1=⍴⍴V
  W←(1,(1↓W)>¯1↓W)/W←V[⍋V]
∇
