∇X←N GPCYCIN C;Y;I;D;U
  ⍝ CONSTRUCTS THE VECTOR FORM OF THE PERMUTATION OF  ⍳N
  ⍝ GIVEN AS A PRODUCT OF CYCLES IN THE CHARACTER VECTOR  C.
  ⍝ THE CYCLES DO NOT NEED TO BE DISJOINT.  ORIGIN DEPENDENT.
  DERR(1=⍴N)∧N=⌊N←,N
  X←⍳N
  C←(C≠' ')/C←,C
  ⍝ GET THE NEXT CYCLE.
LOOP:→(0=⍴C)/0
  D←(I←(C⍳')')+1-⎕IO)↑C
  C←I↓C
  DERR('('=1↑D)∧')'=¯1↑D
  D←¯1↓1↓D
  D[(D=',')/⍳⍴D]←' '
  DERR∧/D∊'0123456789'
  DERR(⍴U)=⍴SSORT U←,¯D
  DERR∧/U<N+⎕IO
  Y←⍳N
  Y[U]←1⌽U
  X←Y[X]
  →LOOP
∇
